version: '3.7'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./src/:/usr/src/app
    links:
      - mongodb

  mongodb:
   image: mongo:3.6.3
